language: python
python:
  - "2.6"
  - "2.7"
install: 
  - "pip install -r requirements.pip --use-mirrors"
  - "pip install coveralls --use-mirrors"
script:
  - coverage run --source=spammy `which trial` spammy
after_success:
  - coveralls
